services:
    db:
        image: postgres
        container_name: db
        networks:
            - private-net
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        env_file: .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    redis:
        image: 'redis:7.4'
        ports:
            - '6379:6379'

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - '8087:80'
        depends_on:
            - db
        volumes:
            - pgadmin_data:/var/lib/pgadmin4
        networks:
            - private-net

networks:
    private-net:
volumes:
    pgdata:
    pgadmin_data: